export const allCards = [
  { id: 1,   name: "Animated Bones",          image: "Animated_Bones.jpg",           mana: 2, attack: 1, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 2,   name: "Astor Demon",             image: "Astor_demon.jpg",              mana: 5, attack: 5, hp: 4,  rarity: "epic",      keywords: ["Apex"] },
  { id: 3,   name: "Bat",                     image: "Bat.jpg",                      mana: 1, attack: 1, hp: 1,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 4,   name: "Battlehog",               image: "Battlehog.jpg",                mana: 3, attack: 4, hp: 2,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 5,   name: "Bee",                     image: "Bee.jpg",                      mana: 1, attack: 2, hp: 1,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 6,   name: "Blackarmor Widow",        image: "Blackarmor_widow.jpg",         mana: 4, attack: 3, hp: 4,  rarity: "rare",      keywords: [] },
  { id: 7,   name: "Blademaster Djinn",       image: "Blademaster_Djinn.jpg",        mana: 6, attack: 6, hp: 5,  rarity: "epic",      keywords: ["Ambush"] },
  { id: 8,   name: "Blizzard Beast",          image: "Blizzard_Beast.jpg",           mana: 5, attack: 5, hp: 5,  rarity: "epic",      keywords: ["Warden"] },
  { id: 9,   name: "Bloodthirsty Kaiman",     image: "Bloodthirsty_Kaiman.jpg",      mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Leech"] },
  { id: 10,  name: "Boar Runt",               image: "Boar_Runt.jpg",                mana: 1, attack: 2, hp: 1,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 11,  name: "Bog Spider",              image: "Bog_Spider.jpg",               mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 12,  name: "Bog Spiderling",          image: "Bog_Spiderling.jpg",           mana: 1, attack: 1, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 13,  name: "Bone Gazer",              image: "Bone_Gazer.jpg",               mana: 3, attack: 2, hp: 4,  rarity: "uncommon",  keywords: ["Omen"] },
  { id: 14,  name: "Borogorom",               image: "Borogorom.jpg",                mana: 8, attack: 8, hp: 8,  rarity: "legendary", keywords: ["Warden", "Apex"] },
  { id: 15,  name: "Brotherhood Captain",     image: "Brotherhood_Captain.jpg",      mana: 4, attack: 4, hp: 4,  rarity: "rare",      keywords: ["Warden"] },
  { id: 16,  name: "Brotherhood Marksman",    image: "Brotherhood_marksman.jpg",     mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 17,  name: "Brotherhood Mender",      image: "Brotherhood_Mender.jpg",       mana: 2, attack: 1, hp: 4,  rarity: "uncommon",  keywords: [] },
  { id: 18,  name: "Brotherhood Sorcerer",    image: "Brotherhood_Sorcerer.jpg",     mana: 4, attack: 3, hp: 4,  rarity: "rare",      keywords: ["Omen"] },
  { id: 19,  name: "Brotherhood Swordsman",   image: "Brotherhood_Swordsman.jpg",    mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 20,  name: "Brotherhood Tracker",     image: "Brotherhood_tracker.jpg",      mana: 3, attack: 3, hp: 3,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 21,  name: "Captain Boone",           image: "Captain_Boone.jpg",            mana: 6, attack: 5, hp: 6,  rarity: "legendary", keywords: ["Ambush", "Apex"] },
  { id: 22,  name: "Cave Spider",             image: "Cave_Spider.jpg",              mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 23,  name: "Chainwraith Creep",       image: "Chainwraith_Creep.jpg",        mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 24,  name: "Chainwraith Haunt",       image: "Chainwraith_haunt.jpg",        mana: 3, attack: 3, hp: 3,  rarity: "rare",      keywords: ["Ambush", "Hollow"] },
  { id: 25,  name: "Chainwraith Prowler",     image: "Chainwraith_Prowler.jpg",      mana: 4, attack: 4, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 26,  name: "Coal Contraption",        image: "Coal_Contraption.jpg",         mana: 3, attack: 3, hp: 4,  rarity: "uncommon",  keywords: [] },
  { id: 27,  name: "Coldstone Cub",           image: "Coldstone_Cub.jpg",            mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 28,  name: "Contagious Sporewalker",  image: "Contagious_Sporewalker.jpg",   mana: 3, attack: 2, hp: 5,  rarity: "rare",      keywords: ["Hollow"] },
  { id: 29,  name: "Crowman",                 image: "Crowman.jpg",                  mana: 3, attack: 3, hp: 3,  rarity: "uncommon",  keywords: ["Omen"] },
  { id: 30,  name: "Crow Matriarch",          image: "Crow_Matriarch.jpg",           mana: 5, attack: 4, hp: 5,  rarity: "epic",      keywords: ["Omen", "Warden"] },
  { id: 31,  name: "Direhorn Drake",          image: "Direhorn_Drake.jpg",           mana: 6, attack: 6, hp: 6,  rarity: "epic",      keywords: ["Apex"] },
  { id: 32,  name: "Dire Bear",               image: "Dire_Bear.jpg",                mana: 5, attack: 6, hp: 5,  rarity: "rare",      keywords: ["Warden"] },
  { id: 33,  name: "Dire Wolf",               image: "Dire_Wolf.jpg",                mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 34,  name: "Doom Gazer",              image: "Doom_Gazer.jpg",               mana: 5, attack: 4, hp: 6,  rarity: "epic",      keywords: ["Omen"] },
  { id: 35,  name: "Draconic Crusader",       image: "Draconic_Crusader.jpg",        mana: 5, attack: 5, hp: 5,  rarity: "epic",      keywords: ["Warden"] },
  { id: 36,  name: "Draconic Pyromancer",     image: "Draconic_Pyromancer.jpg",      mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Apex"] },
  { id: 37,  name: "Dwarf Commoner",          image: "Dwarf_Commoner.jpg",           mana: 1, attack: 1, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 38,  name: "Dwarf Elementalist",      image: "Dwarf_elementalist.jpg",       mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: [] },
  { id: 39,  name: "Dwarf Legionnaire",       image: "Dwarf_Legionnaire.jpg",        mana: 3, attack: 3, hp: 4,  rarity: "uncommon",  keywords: ["Warden"] },
  { id: 40,  name: "Dwarf Mechanic",          image: "Dwarf_Mechanic.jpg",           mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 41,  name: "Dwarf Prospector",        image: "Dwarf_Prospector.jpg",         mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 42,  name: "Dwarf Thunderer",         image: "Dwarf_Thunderer.jpg",          mana: 4, attack: 4, hp: 3,  rarity: "rare",      keywords: ["Apex"] },
  { id: 43,  name: "Dwarf Warrior",           image: "Dwarf_Warrior.jpg",            mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 44,  name: "Elderwood Goliath",       image: "Elderwood_goliath.jpg",        mana: 7, attack: 7, hp: 7,  rarity: "legendary", keywords: ["Warden", "Hollow"] },
  { id: 45,  name: "Elf Assassin",            image: "Elf_Assassin.jpg",             mana: 4, attack: 5, hp: 2,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 46,  name: "Elf Bowman",              image: "Elf_Bowman.jpg",               mana: 2, attack: 3, hp: 1,  rarity: "uncommon",  keywords: [] },
  { id: 47,  name: "Elf Druid",               image: "Elf_Druid.jpg",                mana: 3, attack: 2, hp: 4,  rarity: "uncommon",  keywords: ["Omen"] },
  { id: 48,  name: "Emberglow Trunk",         image: "Emberglow_Trunk.jpg",          mana: 4, attack: 3, hp: 6,  rarity: "rare",      keywords: ["Warden"] },
  { id: 49,  name: "Emberscale Drake",        image: "Emberscale_Drake.jpg",         mana: 6, attack: 6, hp: 5,  rarity: "epic",      keywords: ["Apex"] },
  { id: 50,  name: "Flamelord Djinn",         image: "Flamelord_Djinn.jpg",          mana: 7, attack: 7, hp: 6,  rarity: "legendary", keywords: ["Apex", "Ambush"] },
  { id: 51,  name: "Forest Spider",           image: "Forest_Spider.jpg",            mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 52,  name: "Froll Cryomancer",        image: "Froll_Cryomancer.jpg",         mana: 5, attack: 4, hp: 5,  rarity: "epic",      keywords: [] },
  { id: 53,  name: "Froll Gladiator",         image: "Froll_Gladiator.jpg",          mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 54,  name: "Frostbound Drake",        image: "Frostbound_Drake.jpg",         mana: 5, attack: 5, hp: 5,  rarity: "epic",      keywords: ["Warden"] },
  { id: 55,  name: "Frostrisen Magus",        image: "Frostrisen_Magus.jpg",         mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: ["Omen"] },
  { id: 56,  name: "Frostrisen Shardshooter", image: "Frostrisen_Shardshooter.jpg",  mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 57,  name: "Ghaz Archer",             image: "Ghaz_Archer.jpg",              mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 58,  name: "Ghaz Dino Raider",        image: "Ghaz_Dino_Raider.jpg",         mana: 5, attack: 5, hp: 4,  rarity: "epic",      keywords: ["Ambush"] },
  { id: 59,  name: "Ghaz Sandbender",         image: "Ghaz_Sandbender.jpg",          mana: 3, attack: 3, hp: 4,  rarity: "rare",      keywords: [] },
  { id: 60,  name: "Ghostlamp Hag",           image: "Ghostlamp_Hag.jpg",            mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: ["Omen"] },
  { id: 61,  name: "Glutton Hag",             image: "Glutton_hag.jpg",              mana: 4, attack: 4, hp: 4,  rarity: "rare",      keywords: ["Leech"] },
  { id: 62,  name: "Goblin Berserker",        image: "Goblin_Berserker.jpg",         mana: 2, attack: 3, hp: 1,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 63,  name: "Goblin Bomber",           image: "Goblin_Bomber.jpg",            mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 64,  name: "Goblin Glider",           image: "Goblin_Glider.jpg",            mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 65,  name: "Goblin Pyro",             image: "Goblin_Pyro.jpg",              mana: 3, attack: 4, hp: 2,  rarity: "rare",      keywords: ["Apex"] },
  { id: 66,  name: "Goblin Tinker",           image: "Goblin_Tinker.jpg",            mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 67,  name: "Goblin Wizard",           image: "Goblin_Wizard.jpg",            mana: 3, attack: 3, hp: 3,  rarity: "rare",      keywords: ["Omen"] },
  { id: 68,  name: "Golden Guardian",         image: "Golden_Guardian.jpg",          mana: 7, attack: 6, hp: 8,  rarity: "legendary", keywords: ["Warden"] },
  { id: 69,  name: "Grey Wolf",               image: "Grey_Wolf.jpg",                mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 70,  name: "Harvester Hag",           image: "Harvester_Hag.jpg",            mana: 3, attack: 3, hp: 4,  rarity: "rare",      keywords: ["Leech"] },
  { id: 71,  name: "Hell Gazer",              image: "Hell_Gazer.jpg",               mana: 5, attack: 5, hp: 5,  rarity: "epic",      keywords: ["Omen", "Apex"] },
  { id: 72,  name: "Hierophant Sigrid",       image: "Hierophant_Sigrid.jpg",        mana: 7, attack: 5, hp: 8,  rarity: "legendary", keywords: ["Warden", "Omen"] },
  { id: 73,  name: "High Elf Champion",       image: "High_Elf_Champion.jpg",        mana: 5, attack: 5, hp: 4,  rarity: "epic",      keywords: ["Ambush"] },
  { id: 74,  name: "High Elf Priestess",      image: "high_elf_priestess.jpg",       mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: ["Omen"] },
  { id: 75,  name: "Hobgoblin",               image: "Hobgoblin.jpg",                mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 76,  name: "Hoghound Archer",         image: "Hoghound_archer.jpg",          mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 77,  name: "Hoghound Raider",         image: "Hoghound_Raider.jpg",          mana: 3, attack: 3, hp: 3,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 78,  name: "Hoghound Shaman",         image: "Hoghound_Shaman.jpg",          mana: 4, attack: 3, hp: 4,  rarity: "rare",      keywords: ["Omen"] },
  { id: 79,  name: "Hoglet",                  image: "Hoglet.jpg",                   mana: 1, attack: 1, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 80,  name: "Hog Cultist",             image: "Hog_Cultist.jpg",              mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 81,  name: "Hog Saboteur",            image: "Hog_Saboteur.jpg",             mana: 3, attack: 3, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 82,  name: "Hog Warlord",             image: "Hog_Warlord.jpg",              mana: 5, attack: 6, hp: 4,  rarity: "epic",      keywords: ["Ambush", "Apex"] },
  { id: 83,  name: "Hookmask Doctor",         image: "Hookmask_Doctor.jpg",          mana: 3, attack: 2, hp: 4,  rarity: "rare",      keywords: [] },
  { id: 84,  name: "Hookmask Killer",         image: "Hookmask_Killer.jpg",          mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 85,  name: "Hookmask Knave",          image: "Hookmask_Knave.jpg",           mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 86,  name: "Hookmask Slinger",        image: "Hookmask_Slinger.jpg",         mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 87,  name: "Iceforge Frostcaller",    image: "Iceforge_frostcaller.jpg",     mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: [] },
  { id: 88,  name: "Iceforge Hallkeeper",     image: "Iceforge_Hallkeeper.jpg",      mana: 3, attack: 2, hp: 5,  rarity: "uncommon",  keywords: ["Warden"] },
  { id: 89,  name: "Iceforge Hunter",         image: "Iceforge_Hunter.jpg",          mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 90,  name: "Iceforge Stormgunner",    image: "Iceforge_Stormgunner.jpg",     mana: 4, attack: 4, hp: 4,  rarity: "rare",      keywords: [] },
  { id: 91,  name: "Iceforge Winterlord",     image: "Iceforge_Winterlord.jpg",      mana: 6, attack: 5, hp: 7,  rarity: "epic",      keywords: ["Warden"] },
  { id: 92,  name: "Iceshell Giant",          image: "Iceshell_Giant.jpg",           mana: 6, attack: 5, hp: 8,  rarity: "epic",      keywords: ["Warden"] },
  { id: 93,  name: "Icicle Gazer",            image: "Icicle_Gazer.jpg",             mana: 4, attack: 3, hp: 6,  rarity: "rare",      keywords: ["Omen"] },
  { id: 94,  name: "Kaiman Ambusher",         image: "Kaiman_Ambusher.jpg",          mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 95,  name: "Kaiman Illusionist",      image: "Kaiman_Illusionist.jpg",       mana: 5, attack: 4, hp: 5,  rarity: "epic",      keywords: ["Omen"] },
  { id: 96,  name: "Kaiman Seer",             image: "Kaiman_Seer.jpg",              mana: 3, attack: 2, hp: 4,  rarity: "uncommon",  keywords: ["Omen"] },
  { id: 97,  name: "Manastorm Djinn",         image: "Manastorm_Djinn.jpg",          mana: 6, attack: 6, hp: 5,  rarity: "epic",      keywords: ["Apex"] },
  { id: 98,  name: "Many-eyes Trunk",         image: "Many-eyes_Trunk.jpg",          mana: 5, attack: 4, hp: 6,  rarity: "rare",      keywords: ["Omen", "Warden"] },
  { id: 99,  name: "Mindslave Taskmaster",    image: "Mindslave_Taskmaster.jpg",     mana: 5, attack: 5, hp: 4,  rarity: "epic",      keywords: ["Omen"] },
  { id: 100, name: "Minotaur Arbalist",       image: "Minotaur_Arbalist.jpg",        mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 101, name: "Minotaur Champion",       image: "Minotaur_Champion.jpg",        mana: 5, attack: 6, hp: 5,  rarity: "epic",      keywords: ["Warden", "Apex"] },
  { id: 102, name: "Minotaur Duelist",        image: "Minotaur_Duelist.jpg",         mana: 3, attack: 4, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 103, name: "Minotaur Warden",         image: "Minotaur_Warden.jpg",          mana: 4, attack: 3, hp: 6,  rarity: "rare",      keywords: ["Warden"] },
  { id: 104, name: "Mistycap Mushroom",       image: "Mistycap_Mushroom.jpg",        mana: 2, attack: 1, hp: 4,  rarity: "uncommon",  keywords: ["Hollow"] },
  { id: 105, name: "Moonblade Jackal",        image: "Moonblade_Jackal.jpg",         mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 106, name: "Morningfox Cub",          image: "Morningfox_Cub.jpg",           mana: 1, attack: 1, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 107, name: "Morningfox Ninetails",    image: "Morningfox_Ninetails.jpg",     mana: 6, attack: 5, hp: 6,  rarity: "legendary", keywords: ["Omen", "Leech"] },
  { id: 108, name: "Morningstar Bishop",      image: "Morningstar_Bishop.jpg",       mana: 5, attack: 4, hp: 6,  rarity: "epic",      keywords: ["Warden", "Leech"] },
  { id: 109, name: "Morningstar Flagellant",  image: "Morningstar_Flagellant.jpg",   mana: 3, attack: 4, hp: 3,  rarity: "rare",      keywords: ["Leech"] },
  { id: 110, name: "Morningstar Hermit",      image: "Morningstar_Hermit.jpg",       mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 111, name: "Morningstar Judge",       image: "Morningstar_Judge.jpg",        mana: 6, attack: 5, hp: 7,  rarity: "legendary", keywords: ["Warden", "Apex"] },
  { id: 112, name: "Morningstar Paladin",     image: "Morningstar_Paladin.jpg",      mana: 4, attack: 4, hp: 5,  rarity: "rare",      keywords: ["Warden"] },
  { id: 113, name: "Naturalist Mage",         image: "Naturalist_Mage.jpg",          mana: 3, attack: 3, hp: 4,  rarity: "uncommon",  keywords: [] },
  { id: 114, name: "Naturalist Praiser",      image: "Naturalist_Praiser.jpg",       mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 115, name: "Orc Chieftain",           image: "Orc_Chieftain.jpg",            mana: 6, attack: 6, hp: 6,  rarity: "epic",      keywords: ["Warden", "Ambush"] },
  { id: 116, name: "Orc Nightstar",           image: "Orc_Nightstar.jpg",            mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 117, name: "Orc Spellcaster",         image: "Orc_spellcaster.jpg",          mana: 3, attack: 3, hp: 4,  rarity: "uncommon",  keywords: [] },
  { id: 118, name: "Orc Witchdoctor",         image: "Orc_Witchdoctor.jpg",          mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: ["Omen"] },
  { id: 119, name: "Pearlshell Giant",        image: "Pearlshell_Giant.jpg",         mana: 7, attack: 6, hp: 8,  rarity: "legendary", keywords: ["Warden"] },
  { id: 120, name: "Phoenix",                 image: "Phoenix.jpg",                  mana: 7, attack: 7, hp: 6,  rarity: "legendary", keywords: ["Hollow", "Apex"] },
  { id: 121, name: "Pirate Cannoneer",        image: "Pirate_Cannoneer.jpg",         mana: 4, attack: 5, hp: 2,  rarity: "epic",      keywords: ["Apex"] },
  { id: 122, name: "Pirate Freebooter",       image: "Pirate_freebooter.jpg",        mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 123, name: "Pirate Swashbuckler",     image: "Pirate_Swashbuckler.jpg",      mana: 3, attack: 4, hp: 2,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 124, name: "Poisonpetal Goliath",     image: "Poisonpetal_goliath.jpg",      mana: 7, attack: 6, hp: 7,  rarity: "legendary", keywords: ["Warden", "Hollow"] },
  { id: 125, name: "Poisonpetal Lotus",       image: "Poisonpetal_Lotus.jpg",        mana: 3, attack: 2, hp: 5,  rarity: "uncommon",  keywords: ["Hollow"] },
  { id: 126, name: "Polar Bear",              image: "Polar_Bear.jpg",               mana: 3, attack: 3, hp: 4,  rarity: "rare",      keywords: ["Warden"] },
  { id: 127, name: "Pummeldillo Boxer",       image: "Pummeldillo_Boxer.jpg",        mana: 3, attack: 4, hp: 3,  rarity: "rare",      keywords: [] },
  { id: 128, name: "Queen Snow Spider",       image: "Queen snow spider.jpg",        mana: 6, attack: 5, hp: 7,  rarity: "legendary", keywords: ["Hollow", "Omen"] },
  { id: 129, name: "Rargum the Dread",        image: "Rargum_the_Dread.jpg",         mana: 7, attack: 7, hp: 6,  rarity: "legendary", keywords: ["Apex", "Ambush"] },
  { id: 130, name: "Rat Burglar",             image: "Rat_burglar.jpg",              mana: 1, attack: 2, hp: 1,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 131, name: "Rat Scavenger",           image: "Rat_Scavenger.jpg",            mana: 1, attack: 1, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 132, name: "Rat Spiketail",           image: "Rat_spiketail.jpg",            mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 133, name: "Rubycap Mushroom",        image: "Rubycap_Mushroom.jpg",         mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: ["Hollow"] },
  { id: 134, name: "Runegust Jackal",         image: "Runegust_jackal.jpg",          mana: 3, attack: 3, hp: 3,  rarity: "rare",      keywords: [] },
  { id: 135, name: "Saltdusk Bloodmage",      image: "Saltdusk_Bloodmage.jpg",       mana: 5, attack: 5, hp: 4,  rarity: "epic",      keywords: ["Leech", "Apex"] },
  { id: 136, name: "Saltdusk Cutthroat",      image: "Saltdusk_Cutthroat.jpg",       mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 137, name: "Saltdusk Executioner",    image: "Saltdusk_Executioner.jpg",     mana: 5, attack: 6, hp: 4,  rarity: "epic",      keywords: ["Ambush"] },
  { id: 138, name: "Saltdusk Ritualist",      image: "Saltdusk_Ritualist.jpg",       mana: 4, attack: 3, hp: 5,  rarity: "rare",      keywords: ["Leech", "Omen"] },
  { id: 139, name: "Sandwatcher Jackal",      image: "Sandwatcher_Jackal.jpg",       mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 140, name: "Saurian Monitor",         image: "Saurian_Monitor.jpg",          mana: 3, attack: 3, hp: 4,  rarity: "uncommon",  keywords: [] },
  { id: 141, name: "Saurian Scaleshield",     image: "Saurian_Scaleshield.jpg",      mana: 4, attack: 3, hp: 6,  rarity: "rare",      keywords: ["Warden"] },
  { id: 142, name: "Saurian Skullmage",       image: "Saurian_Skullmage.jpg",        mana: 4, attack: 4, hp: 4,  rarity: "rare",      keywords: ["Omen"] },
  { id: 143, name: "Saurian Sungazer",        image: "Saurian_Sungazer.jpg",         mana: 3, attack: 3, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 144, name: "Shadowfox Ninetails",     image: "Shadowfox_Ninetails.jpg",      mana: 6, attack: 5, hp: 6,  rarity: "legendary", keywords: ["Ambush", "Leech"] },
  { id: 145, name: "Shark Goldfin",           image: "Shark_Goldfin.jpg",            mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 146, name: "Shark Harpooner",         image: "Shark_Harpooner.jpg",          mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 147, name: "Shark Hydromancer",       image: "Shark_Hydromancer.jpg",        mana: 5, attack: 4, hp: 5,  rarity: "epic",      keywords: [] },
  { id: 148, name: "Sharpweed Trunk",         image: "Sharpweed_Trunk.jpg",          mana: 4, attack: 4, hp: 5,  rarity: "rare",      keywords: ["Warden"] },
  { id: 149, name: "Skeleton",                image: "Skeleton.jpg",                 mana: 1, attack: 1, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 150, name: "Skeleton Archer",         image: "Skeleton_archer.jpg",          mana: 2, attack: 3, hp: 1,  rarity: "uncommon",  keywords: [] },
  { id: 151, name: "Skeleton Haunt",          image: "Skeleton_Haunt.jpg",           mana: 2, attack: 2, hp: 2,  rarity: "uncommon",  keywords: ["Hollow"] },
  { id: 152, name: "Skeleton Pikeman",        image: "Skeleton_Pikeman.jpg",         mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 153, name: "Skeleton Raider",         image: "Skeleton_Raider.jpg",          mana: 3, attack: 3, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 154, name: "Skeleton Rothclub",       image: "Skeleton_Rothclub.jpg",        mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 155, name: "Skeleton Soldier",        image: "Skeleton_Soldier.jpg",         mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 156, name: "Skorn Acolyte",           image: "Skorn_Acolyte.jpg",            mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 157, name: "Skorn Deathblade",        image: "Skorn_Deathblade.jpg",         mana: 5, attack: 6, hp: 4,  rarity: "epic",      keywords: ["Ambush", "Leech"] },
  { id: 158, name: "Skorn Grandmaster",       image: "Skorn_Grandmaster.jpg",        mana: 7, attack: 6, hp: 7,  rarity: "legendary", keywords: ["Warden", "Leech"] },
  { id: 159, name: "Skorn Initiate",          image: "Skorn_Initiate.jpg",           mana: 2, attack: 2, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 160, name: "Skorn Warlock",           image: "Skorn_Warlock.jpg",            mana: 4, attack: 4, hp: 4,  rarity: "rare",      keywords: ["Leech"] },
  { id: 161, name: "Spearhog",                image: "Spearhog.jpg",                 mana: 3, attack: 4, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 162, name: "Spellslayer Drake",       image: "Spellslayer_Drake.jpg",        mana: 6, attack: 6, hp: 5,  rarity: "epic",      keywords: ["Apex"] },
  { id: 163, name: "Sunchaser Jackal",        image: "Sunchaser_Jackal.jpg",         mana: 3, attack: 3, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 164, name: "Toad",                    image: "Toad.jpg",                     mana: 1, attack: 1, hp: 2,  rarity: "uncommon",  keywords: [] },
  { id: 165, name: "Toadstool Shaman",        image: "Toadstool_Shaman.jpg",         mana: 3, attack: 2, hp: 4,  rarity: "rare",      keywords: ["Omen"] },
  { id: 166, name: "Toadstool Warrior",       image: "Toadstool_Warrior.jpg",        mana: 3, attack: 3, hp: 4,  rarity: "uncommon",  keywords: [] },
  { id: 167, name: "Toad Ambusher",           image: "Toad_ambusher.jpg",            mana: 2, attack: 3, hp: 2,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 168, name: "Toad Enforcer",           image: "Toad_Enforcer.jpg",            mana: 3, attack: 3, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 169, name: "Toad Executioner",        image: "Toad_Executioner.jpg",         mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Ambush"] },
  { id: 170, name: "Toad Farseer",            image: "Toad_Farseer.jpg",             mana: 3, attack: 2, hp: 4,  rarity: "uncommon",  keywords: ["Omen"] },
  { id: 171, name: "Toad Sentinel",           image: "Toad_Sentinel.jpg",            mana: 2, attack: 1, hp: 4,  rarity: "uncommon",  keywords: ["Warden"] },
  { id: 172, name: "Troll",                   image: "Troll.jpg",                    mana: 4, attack: 4, hp: 5,  rarity: "uncommon",  keywords: [] },
  { id: 173, name: "Troll Brawler",           image: "Troll_Brawler.jpg",            mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: [] },
  { id: 174, name: "Troll Champion",          image: "Troll_champion.jpg",           mana: 5, attack: 5, hp: 6,  rarity: "epic",      keywords: ["Warden"] },
  { id: 175, name: "Troll Knight",            image: "Troll_Knight.jpg",             mana: 5, attack: 4, hp: 6,  rarity: "rare",      keywords: ["Warden"] },
  { id: 176, name: "Troll Titan",             image: "Troll_Titan.jpg",              mana: 8, attack: 8, hp: 8,  rarity: "legendary", keywords: ["Warden", "Apex"] },
  { id: 177, name: "Troll Warlock",           image: "Troll_Warlock.jpg",            mana: 4, attack: 4, hp: 5,  rarity: "rare",      keywords: ["Leech"] },
  { id: 178, name: "Twinhead Yeti",           image: "Twinhead_Yeti.jpg",            mana: 6, attack: 6, hp: 6,  rarity: "epic",      keywords: ["Warden"] },
  { id: 179, name: "Vampire Necromancer",     image: "Vampire_Necromancer.jpg",      mana: 5, attack: 4, hp: 5,  rarity: "epic",      keywords: ["Leech", "Hollow"] },
  { id: 180, name: "Vampire Reaver",          image: "Vampire_Reaver.jpg",           mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Leech", "Ambush"] },
  { id: 181, name: "Vampire Vixen",           image: "Vampire_Vixen.jpg",            mana: 3, attack: 4, hp: 3,  rarity: "rare",      keywords: ["Leech"] },
  { id: 182, name: "Venomous Contraption",    image: "Venomous_contraption.jpg",     mana: 3, attack: 3, hp: 4,  rarity: "rare",      keywords: ["Hollow"] },
  { id: 183, name: "Vermurat",                image: "Vermurat.jpg",                 mana: 6, attack: 6, hp: 6,  rarity: "legendary", keywords: ["Apex", "Leech"] },
  { id: 184, name: "Vile Wurm",               image: "Vile_wurm.jpg",                mana: 5, attack: 5, hp: 5,  rarity: "epic",      keywords: ["Leech"] },
  { id: 185, name: "Warlock Ezanor",          image: "Warlock_Ezanor.jpg",           mana: 7, attack: 6, hp: 7,  rarity: "legendary", keywords: ["Apex", "Omen"] },
  { id: 186, name: "Wildfire Jackal",         image: "Wildfire_Jackal.jpg",          mana: 4, attack: 5, hp: 3,  rarity: "rare",      keywords: ["Ambush", "Apex"] },
  { id: 187, name: "Winterborn Guardian",     image: "Winterborn_Guardian.jpg",      mana: 4, attack: 3, hp: 6,  rarity: "rare",      keywords: ["Warden"] },
  { id: 188, name: "Winterborn Hunter",       image: "Winterborn_Hunter.jpg",        mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 189, name: "Winterborn Shaman",       image: "Winterborn_Shaman.jpg",        mana: 4, attack: 3, hp: 5,  rarity: "epic",      keywords: ["Omen"] },
  { id: 190, name: "Yornish Druid",           image: "Yornish_Druid.jpg",            mana: 3, attack: 2, hp: 5,  rarity: "rare",      keywords: ["Omen"] },
  { id: 191, name: "Yornish Frostbearer",     image: "Yornish_Frostbearer.jpg",      mana: 5, attack: 4, hp: 6,  rarity: "epic",      keywords: ["Warden"] },
  { id: 192, name: "Yornish Hunter",          image: "Yornish_Hunter.jpg",           mana: 3, attack: 4, hp: 3,  rarity: "uncommon",  keywords: ["Ambush"] },
  { id: 193, name: "Zorian Hailbringer",      image: "Zorian_Hailbringer.jpg",       mana: 5, attack: 5, hp: 5,  rarity: "epic",      keywords: ["Apex"] },
  { id: 194, name: "Zorian Shoreguard",       image: "Zorian_Shoreguard.jpg",        mana: 4, attack: 3, hp: 6,  rarity: "rare",      keywords: ["Warden"] },
  { id: 195, name: "Zorian Stormcaller",      image: "Zorian_Stormcaller.jpg",       mana: 5, attack: 5, hp: 4,  rarity: "epic",      keywords: ["Apex"] },
]