export const allHeroes = [
  {
    id: 'skorn',
    name: 'Lord Skorn the Wicked',
    color: '#1a1a1a',
    borderColor: '#555555',
    glowColor: 'rgba(80,80,80,0.6)',
    image: 'lordofskorn.webp',
    passive: 'Warden creatures gain +1 HP when played.',
    abilityName: 'Fortify',
    abilityCost: 2,
    abilityDesc: 'Give a friendly creature +2 HP.',
    abilityEffect: 'fortify',
  },
  {
    id: 'serafine',
    name: 'Serafine the Blood Mistress',
    color: '#8e44ad',
    borderColor: '#c39bd3',
    glowColor: 'rgba(142,68,173,0.6)',
    image: 'serafine.webp',
    passive: 'Draw 1 extra card on your first turn.',
    abilityName: 'Foresight',
    abilityCost: 1,
    abilityDesc: 'Look at the top 3 cards of your deck, keep 1 on top.',
    abilityEffect: 'foresight',
  },
  {
    id: 'blake',
    name: 'Blake, Lord of Blood',
    color: '#c0392b',
    borderColor: '#e74c3c',
    glowColor: 'rgba(192,57,43,0.6)',
    image: 'blake.webp',
    passive: 'Leech creatures heal +1 extra per attack.',
    abilityName: 'Blood Price',
    abilityCost: 2,
    abilityDesc: 'Deal 3 damage to any creature. You lose 1 HP.',
    abilityEffect: 'bloodprice',
  },
  {
    id: 'djinn',
    name: 'Djinn',
    color: '#d4a017',
    borderColor: '#f1c40f',
    glowColor: 'rgba(212,160,23,0.6)',
    image: 'djinn.webp',
    passive: 'Ambush creatures gain +1 attack when played.',
    abilityName: 'Unleash',
    abilityCost: 2,
    abilityDesc: 'Give a friendly creature Ambush until end of turn.',
    abilityEffect: 'unleash',
  },
  {
    id: 'igneas',
    name: 'Igneas',
    color: '#2980b9',
    borderColor: '#5dade2',
    glowColor: 'rgba(41,128,185,0.6)',
    image: 'igneas.webp',
    passive: "Opponent's first turn max mana is reduced by 1.",
    abilityName: 'Glacial Grasp',
    abilityCost: 3,
    abilityDesc: 'Exhaust an enemy creature — it skips its next attack.',
    abilityEffect: 'glacialgrasp',
  },
]